In [16]:
list = [1, 2, 3, 4, 5]  # list operations and methods
print(list)



[1, 2, 3, 4, 5]


In [17]:
subjects = ["Math", "English", "Science", "History", "Art"]
print(subjects)

['Math', 'English', 'Science', 'History', 'Art']


In [18]:
print(subjects[0])
print(subjects[-1])


Math
Art


In [19]:
subjects[2] = "Python"
print(subjects)

['Math', 'English', 'Python', 'History', 'Art']


In [4]:
# list operations and methods 
list = [1, 2, 3, 4, 5]
print(list)



[1, 2, 3, 4, 5]


In [5]:

list.append(6)  # adds an element to the end of the list
list.append(7)
print(list)

[1, 2, 3, 4, 5, 6, 7]


In [13]:

list.insert(2, 5)  # inserts an element at a specific index
print(list)

[1, 2, 5, 3, 4, 6, 7]


In [14]:
#Remove an element from the list
list.remove(5)
print(list)

[1, 2, 3, 4, 6, 7]


In [9]:
#Sort the list
list.sort()
print(list)


[1, 2, 3, 4, 6, 7]


In [15]:
#Revese the list
list.reverse()
print(list)

[7, 6, 4, 3, 2, 1]


In [20]:
#Nested list and matrix Operations
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [28]:
# 3*3 matrix
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        print(matrix[i][j], end=" ")
    print()


1 2 3 
4 5 6 
7 8 9 


In [24]:

for i in range(len(matrix)):
    print(matrix[i])
    

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [45]:
#Add Matrix
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 11, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
result = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [46]:
#Add Matrix

for i in range(len(matrix1)):
    for j in range(len(matrix1[i])):
        result[i][j] = matrix1[i][j] + matrix2[i][j]


In [94]:
for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        print(matrix1[i][j] + matrix2[i][j], end=" ")
    print()


10 10 10 
10 10 10 
10 13 10 


In [100]:
#Matrix Multiplication  
for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        result[i][j] = 0
for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            result[i][j] += matrix1[i][k] * matrix2[k][j]
print("Result of Matrix Multiplication:")
for i in range(len(result)):
    print(result[i])
    

Result of Matrix Multiplication:
[30, 24, 18]
[84, 69, 54]
[156, 129, 102]


In [108]:
# Matrix multiplication using dot() 
import numpy as np
result = np.dot(matrix1, matrix2) 
print("Result:") 
print(result)

Result:
[[ 30  24  18]
 [ 84  69  54]
 [156 129 102]]


In [107]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.
